### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ertogs** [thansen-solire/datatables-light-columnfilter#1]
Hey there, 
just found this column filter plugin. i am looking for a replacement for the default plugin. so i wanted to ask if you have a documentation or some examples how to use this plugin. 

thank you for sharing you work! :)

**Comment by thansen-solire** [comment]
There's an example here : https://github.com/Solire/Trieur. In the dir. Example/
But the configuration is generated in php.

But I am gonna do a doc soon!

**Comment by thansen-solire** [comment]
I've added some documentation in the README.md file.

**Comment by rechl** [comment]
Great! Thank you so much. I will try to implement it with angular datatables and give you feedback.

**Comment by ertogs** [comment]
Works like a charm. To doc was a great start for me. Again thank you.

**Comment by thansen-solire** [comment]
Thanks! If you add some new filter type, don't hesitate to show me!
