### ISSUE TITLE
Reset filters

### ISSUE THREAD

**Issue by StephanieOSZ** [thansen-solire/datatables-light-columnfilter#10]
Hello,
I'd like to know how to reset all filters without change the select. In my datatable I have 5 filters select and I create a button which I want to reset all selects with a single click.
Thanks in advance.

**Comment by stephane-monnot** [comment]
This should work:

``` js
$('table thead tr:eq(1) :input').val('').trigger('change'); // Don't forget to trigger
$('#yourDatatableId').DataTable().ajax.reload();
```

**Comment by stephane-monnot** [comment]
@StephanieOSZ Have you solved your problem ?
