### ISSUE TITLE
Integration with Responsive Plugin

### ISSUE THREAD

**Issue by mustang666** [thansen-solire/datatables-light-columnfilter#12]
When I try to integrate ligth-columnfilter with responsive plugin. The responsive plugin hides columns on resize event, but the filters are still visible.

![dt2](https://cloud.githubusercontent.com/assets/7168978/20560238/22dab606-b170-11e6-98c0-8a47233af057.PNG)
![dt1](https://cloud.githubusercontent.com/assets/7168978/20560239/22f10258-b170-11e6-916f-2cd27da555a1.PNG)

**Comment by thansen-solire** [comment]
this works for me
what version are you using?
