### ISSUE TITLE
[question] Is it possible to trigger search on 'enter' instead of on 'keyup'?

### ISSUE THREAD

**Issue by jeltok** [thansen-solire/datatables-light-columnfilter#14]
Is it possible to trigger search on 'enter' instead of on 'keyup'? The users of my application are a bit old fashioned, and  they want full control on when the actual search will be triggered. In addition we are talking about huge datasets on the server.
Would it be possible to add a configuration that would allow me to define what triggers the actual server side search? E.g. 'enter' (or even a button), vs. on keyup event.

**Comment by thansen-solire** [comment]
Yes I just suggested it in another Issue.
You can add this feature and ask for a pull request. I'll gladly look into it.
