### ISSUE TITLE
Request for add Custom HTML selector

### ISSUE THREAD

**Issue by kushal555** [thansen-solire/datatables-light-columnfilter#16]
Hi,
First of all, i want to say thanks to you for such a good plugin.
Actually, as before I used the columnFilter plugin which is not maintained longer. In that plugin which is provide the facility to set custom search input box where you want.
for that, we need to pass the extra param in columnFilter options 
``{
    html: 'input',
    type: 'text',
    regexp : true,
    sSelector:"#companyName"
  }``

and in HTML you just put the `div` with given id like 
```
<div class="form-group col-md-4">
       <label for="companyName">Company Name</label>
        <div id="companyName"></div>
</div>
```

then it will provide the textbox or dropdown based on type.

**Comment by thansen-solire** [comment]
Hello,
 You can add this feature and ask for a pull request. I'll gladly look into it.
