### ISSUE TITLE
how to change ligh-column-filter's Textbox width. 

### ISSUE THREAD

**Issue by sanchig** [thansen-solire/datatables-light-columnfilter#2]
We are using angular Light-column-filter for serverside processing and it works perfectly as showed in the website. but we want to change the ligh-column-filter's Textbox width and we had tried t change column width but it doesn't work. it works when we don't use light-column-filter. I think it should set width based on column's content (As datatables set column's width based on their content) and it should be responsive. We want to use light-column-filter and We really want to solve these problem. please help and thanks in advance.....

**Comment by stephane-monnot** [comment]
I add a new option "width" to columnConfig to be able to set the width of each filter field in version 0.0.13.
You can use such as below

``` javascript
new $.fn.dataTable.ColumnFilter(dt, {
  0: {
    type: 'text',
    width: '80px' // you can specify a width for each field
  },
  2: {
    type: 'dateRange',
     width: '90px'
  }
});
```

**Comment by sanchig** [comment]
@shinbuntu  First of all Thank you for your great work. I set {width: '100%'} in all my columns (more than 8 columns). and it set auto width based on column width. I think it is best if you set {width: '100%'} by default in the plugin so user doesn't need to set in all columns as I am doing right now.

**Comment by sanchig** [comment]
@shinbuntu  angular-datatables always needs {width: '100%'} for Responsive table. please set {width: '100%'} default value.

**Comment by stephane-monnot** [comment]
@sanchig The default value for width param is now 100% in 0.0.14. Except for date range input, I set to 50% each width's field.

**Comment by sanchig** [comment]
@shinbuntu  thank you very much

**Comment by stephane-monnot** [comment]
@sanchig you're welcome
