### ISSUE TITLE
dateRange "width":"50%" doesn't work

### ISSUE THREAD

**Issue by sanchig** [thansen-solire/datatables-light-columnfilter#5]
in "dateRange" filter "start" and "end" text-boxes takes 100% width instead 50% even if I set initialization time it takes 100%.
4 : { "type" : "dateRange", "width":"50%"}, 

but doesn't work.

In inspect element I got this result

.input-group .form-control {   //bootstrap.css:3859
    position: relative;
    z-index: 2;
    float: left;
    width: 100%;
    margin-bottom: 0;
}

I don't know why it doesn't work with "dateRange" but it works well with "text" and "selection"

**Comment by tatvadevanshi** [comment]
+1
