### ISSUE TITLE
Hide and Show column filter th according to datatable build-in columns visibility is not worked correct

### ISSUE THREAD

**Issue by zhaoyim** [thansen-solire/datatables-light-columnfilter#8]
First, I can not pasted my code in here, because it is a log code.

Problem is:
I try to use the angular datatable light filter which is based on this light filter, I found the Hide and Show column filter th according to datatable build-in columns visibility is not worked correct.

Look into the dataTables.lightColumnFilter.js file line 150
// Hide and Show column filter th according to datatable build-in columns visibility
        $(self.dataTable.table().node()).on('column-visibility.dt', function (e, settings, column, state) {
          if (state) {
            $('th', tr).eq(column -1).show()
          } else {
            $('th', tr).eq(column -1).hide()
          }
        });

Why here use "column -1" in the show and hide, now the angular datatable column index is start from 0, so I think we should use "column" instead of "column -1" , I did this changes, my code worked well, Could you have a look? Thanks a lot!

**Comment by jmtt89** [comment]
Your are right, only need remove that -1 in both lines

I just send a pullRequest to add this bugfix and html5 support for input type :)

**Comment by zhaoyim** [comment]
@jmtt89  Thanks for your confirm!! Just want to know, when the changes will be delivered?

**Comment by thansen-solire** [comment]
Sorry for the delay, I'll look into it today

**Comment by thansen-solire** [comment]
Available in release 1.0.0

**Comment by digroovio** [comment]
The column visibility is working on page load but does not work with the dynamic column visibility using the Buttons plugin. The column filter stays visible when dynamically hiding the column.

**Comment by stephane-monnot** [comment]
@digroovio Could you provide an example please ?

**Comment by digroovio** [comment]
After looking further into it, it does work if all of the columns are visible on page load. But if a column is hidden with DTColumnBuilder notVisible(), then when using the Column visibility button to unhide it, it doesn't display the filter header.
